@host = http://localhost:5000

POST {{host}}/posts
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "title": "My First Blog Post",
  "content": "Lorem ipsum...."
}

###


POST {{host}}/posts/1/support
Accept: application/json
Content-Type: application/json

{
    "postId": 1,
    "supporterId": 1
}


###
