@host = http://localhost:5000

POST {{host}}/api/posts
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "title": "My First Blog Post",
  "content": "Lorem ipsum...."
}

###

POST {{host}}/api/posts/1/support
Accept: application/json
Content-Type: application/json

{
    "postId": 1,
    "supporterId": 1
}


###

GET {{host}}/api/posts/1
Accept: application/json
Content-Type: application/json

###

GET {{host}}/api/dailyhadiths
Accept: application/json
Content-Type: application/json

###

GET {{host}}/api/Bundles/1
Accept: application/json
Content-Type: application/json

###